title: "Bea & Chus"
description: "Nos casamos y queremos celebrarlo contigo"
wedding_date: "28 de noviembre de 2026"
wedding_location: "A Coruna"
url: "https://bodabyc-28-11.github.io"
baseurl: ""
lang: "es"
timezone: "Europe/Madrid"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md